### ISSUE TITLE
생산/수입/공급중단 보고 의약품, 생산/수입/공급부족 보고 의약품 크롤러

### ISSUE THREAD

**Issue by hoony-o-1** [sluggishhackers/issues#3]
# 참고
https://github.com/sluggishhackers/crawlers-ts

**Comment by avecjoeun** [comment]
단체명: 건강사회를위한약사회
관련 서비스: 크롤러
담당 멘토: 후니
작업 상태: 의뢰 완료
활동가: 이동근
