### ISSUE TITLE
구글스프레드시트에 저장된 복수의 데이터를 공통템플릿 pdf에 반영하여 구글 드라이브에 저장하기

### ISSUE THREAD

**Issue by hoony-o-1** [sluggishhackers/issues#6]
# 준비물
* 후원회원 목록이 담긴 엑셀 파일 1개 (컬럼은 맞춰주시되, 실 데이터가 아닌 더미 데이터로 넣어주세요)
* 템플릿 슬라이드 1개
* 생성한 슬라이드를 저장할 구글 폴더 ID
> 폴더 ID는 url 에서 확인하실 수 있습니다. https://drive.google.com/drive/folders/<폴더ID>/

# 사용법
* 코드를 직접 수정해야하는 부분이 있으니 적용 의뢰는 이메일(갱, [kninami@gmail.com](mailto:kninami@gmail.com))로 문의주세요.
* 엑셀 시트 상단에 Sluggish Hackers 메뉴가 생성된 것을 확인할 수 있습니다.
<img width="830" alt="excel" src="https://github.com/sluggishhackers/issues/assets/5093263/0ab75db8-0477-4d05-803f-0b28ecfd486a">

* 메뉴를 클릭하고, pdf로 변환할 행 번호를 클릭하면 입력하면 전달해주신 구글 폴더 하위에 pdf 파일이 자동 생성됩니다.
<img width="527" alt="스크린샷 2023-08-25 오후 12 18 33" src="https://github.com/sluggishhackers/issues/assets/5093263/da3cc55e-682a-419c-bbaa-f89881ed3978">

* 베이스 소스코드는 [링크](https://gist.github.com/kninami/ea334f769ae13ad1e9e0bd8e50e101b7)에서 확인하실 수 있습니다.

# 함께 한 단체
* 서울환경연합
* 녹색연합

**Comment by kninami** [comment]
### 준비물
* 후원회원 목록이 담긴 엑셀 파일 1개 
* 템플릿 슬라이드 1개 
* 생성한 슬라이드를 저장할 구글 폴더 ID 
> 폴더 ID는 url 에서 확인하실 수  있습니다. https://drive.google.com/drive/folders/**<폴더ID>**/

### 사용법 
* 작업을 의뢰하면, 엑셀 시트 상단에 Sluggish Hackers 메뉴가 생성된 것을 확인할 수 있습니다.
<img width="830" alt="스크린샷 2023-08-25 오후 12 18 14" src="https://github.com/sluggishhackers/issues/assets/5093263/
305327c8-b5b4-4cfa-92b0-c5e8abab6ec2">
* 메뉴를 클릭하고, pdf로 변환할 행 번호를 클릭하면 입력하면 자동생성됩니다.
<img width="527" alt="스크린샷 2023-08-25 오후 12 18 33" src="https://github.com/sluggishhackers/issues/assets/5093263/827bfbc4-232b-40eb-bf3e-ea20832aad41">

### 세팅 가이드 
* 코드를 직접 수정해야하는 부분이 있으니 적용이 필요하신 경우 이메일(kninami@gmail.com)로 문의주세요.
* 베이스 소스코드는 [링크](https://gist.github.com/kninami/ea334f769ae13ad1e9e0bd8e50e101b7)에서 확인하실 수 있습니다.

### 함께 한 단체
* 서울환경연합
* 녹색연합
